"""Module to manage input players data.

The players data is generated by an excel file, which is encoded using base64
and stored below, in the variable `BASE64_DF`.
"""

import base64
import logging
from io import StringIO

import pandas as pd
import pyperclip

logger = logging.getLogger(__name__)

BASE64_DF = (
    "dXVpZCx1c2VybmFtZSxvbmxpbmUNCjQ1MzBkMTNjLWM4ZjMtNDM1MC05YzJkLTM5Mm"
    "FhNTNmMTVlMSxsdXNpY3JhZnQsVHJ1ZQ0KMGM5M2E2NjktODdjZi0zYTZkLTk5Y2Ut"
    "MzI3NTVjMTA1ODdlLGx1c2ljcmFmdCxGYWxzZQ0KNGE2MTg3NjgtNGYyNi00Njg4LT"
    "hhYjUtNmU2NGYyNTBjNjJmLFNyQWxsb3phLFRydWUNCmJlMTc2NDBiLTg0NzEtMzIx"
    "ZS1hMzU1LWQyYTI4NTllYmRhMSxTckFsbG96YSxGYWxzZQ0KYTE5YzI4NDAtY2ZhZS"
    "00OGMxLTk5ZGMtMzQ5MjQ0NDZiMGY0LE1JQ0hBRUxDUkFGNyxUcnVlDQpkNTljMTI4"
    "NS05NDNhLTM0MjItODRiZC0wYjdhZDE2ZTM1YjUsTUlDSEFFTENSQUY3LEZhbHNlDQ"
    "oxMjhhMDliNi1mOGVlLTQyZTItYTdkYy0xZDEyOWYxNGYwZDksQmFidWNoYXMsVHJ1"
    "ZQ0KYjFmYzRmNWMtMDA4Mi0zNjU4LWJiYzgtZjViMWY3YzlmZTBjLEJhYnVjaGFzLE"
    "ZhbHNlDQo3NTU2NWViOC0zYTYxLTRlNzctYmUxOC04MDJjYmFkMGZmMDMsR2FsZXNh"
    "aXpfOTgsVHJ1ZQ0KMDM0YTU1OGEtOGVjYS0zOTZiLWE4ODMtM2Q3OWE5NTZlNDcxLE"
    "dhbGVzYWl6Xzk4LEZhbHNlDQphOTczNWY2Ni1mNzc5LTQ0ZTMtOTc0ZS04MTRkN2Rh"
    "MGU1NGYsVGFua3J1czk4LFRydWUNCjFjMTFlN2IxLWEzZjAtMzRmNy1hOWVlLTBiMj"
    "gzNmE1M2FkMixUYW5rcnVzOTgsRmFsc2UNCjMwOGZjZDI3LTQ5YTgtNDc5NS1hNmEw"
    "LTU2OGVlZjBjYTk2NCxBeGVoOTksVHJ1ZQ0KZWEwYmZjMTItZTI0ZC0zYmI2LTliNG"
    "YtMDhkN2M0NTc2M2UwLEF4ZWg5OSxGYWxzZQ0K"
)

logger.debug("loading dataframe")
_DF = pd.read_csv(
    StringIO(base64.b64decode(BASE64_DF.encode()).decode()), index_col="uuid"
)
logger.debug("dataframe loaded")


def get_uuid(username, mode) -> str:
    """Returns the uuid of a player given its username and online mode.

    Args:
        username (str): username of the player.
        mode (bool): online mode of the player.

    Returns:
        str: uuid of the player.
    """

    mask = (_DF.username == username) & (_DF.online == mode)
    return _DF[mask].iloc[0].name


def get_username(uuid) -> str:
    """Returns the username of a player given its uuid.

    Args:
        uuid (str): uuid of the player.

    Returns:
        str: username of the player.
    """

    return _DF.loc[uuid, "username"]


def get_mode(uuid) -> bool:
    """Returns the mode of a player given its uuid.

    Args:
        uuid (str): uuid of the player.

    Returns:
        bool: online mode of the player.
    """

    return bool(_DF.loc[uuid, "online"])


def get_dataframe() -> pd.DataFrame:
    """Returns the players dataframe.

    Returns:
        pd.DataFrame: dataframe containing uuid, username and online mode of
            each player.
    """

    return _DF.copy()


def excel_to_b64(excel_path: str):
    """Prints and copies to clipboard the base64 representation of the
    excel as a csv.

    Args:
        excel_path (str): filepath of the excel file.
    """

    df = pd.read_excel(excel_path)
    df.set_index("uuid", inplace=True)

    bytes_df = df.to_csv(index="uuid").encode()

    b64data = base64.b64encode(bytes_df).decode()
    print(b64data)
    pyperclip.copy(b64data)
